@@ -50,6 +50,7 @@ int main(int argc, char* argv[])
   /* Prepend header comment.  */
   fprintf(ofp, "/*\n * DO NOT EDIT\n * This file is generated by:\n");
   fprintf(ofp, " * %s\n */\n\n", argv[0]);
+  fprintf(ofp, "#include <Configure.h>\n\n");
   fprintf(ofp, "#include <stdio.h>\n\n");
   
   /* Split file up in 1024-byte chunks.  */
@@ -74,8 +75,8 @@ int main(int argc, char* argv[])
   fclose(ifp);
   
   /* Provide a function to write the data to a file.  */
-  fprintf(ofp, "extern int %sEncodedWriteArray%s(const char* fname)\n",
-          argv[3], argv[4]);
+  fprintf(ofp, "extern %s_EXPORT int %sEncodedWriteArray%s(const char* fname)\n",
+          argv[3], argv[3], argv[4]);
   fprintf(ofp, "{\n");
   fprintf(ofp, "  FILE* ofp = fopen(fname, \"wb\");\n");
   fprintf(ofp, "  if(!ofp) { return 0; }\n");