 int change_dir(const char *dir, int set_path_only);
 char *normalize_path(char *path, BOOL force_newbuf, unsigned int *len_ptr);
 char *full_fname(const char *fn);
 char *partial_dir_fname(const char *fname);
 int handle_partial_dir(const char *fname, int create);
 int unsafe_symlink(const char *dest, const char *src);
-char *human_num(int64 num);
-char *human_dnum(double dnum, int decimal_digits);
 char *timestring(time_t t);
-int msleep(int t);
 int cmp_time(time_t file1, time_t file2);
 int _Insure_trap_error(int a1, int a2, int a3, int a4, int a5, int a6);
-void *_new_array(unsigned long num, unsigned int size, int use_calloc);
-void *_realloc_array(void *ptr, unsigned int size, size_t num);
 const char *find_filename_suffix(const char *fn, int fn_len, int *len_ptr);
-uint32 fuzzy_distance(const char *s1, int len1, const char *s2, int len2);
+uint32 fuzzy_distance(const char *s1, unsigned len1, const char *s2, unsigned len2);
 struct bitbag *bitbag_create(int max_ndx);
 void bitbag_set_bit(struct bitbag *bb, int ndx);
 void bitbag_clear_bit(struct bitbag *bb, int ndx);
 int bitbag_check_bit(struct bitbag *bb, int ndx);
 int bitbag_next_bit(struct bitbag *bb, int after);
 void flist_ndx_push(flist_ndx_list *lp, int ndx);
 int flist_ndx_pop(flist_ndx_list *lp);
 void *expand_item_list(item_list *lp, size_t item_size,
 		       const char *desc, int incr);
+int msleep(int t);
+void *_new_array(unsigned long num, unsigned int size, int use_calloc);
+void *_realloc_array(void *ptr, unsigned int size, size_t num);
+const char *sum_as_hex(const char *sum);
+NORETURN void out_of_memory(const char *str);
+NORETURN void overflow_exit(const char *str);
 void free_xattr(stat_x *sxp);
 int get_xattr(const char *fname, stat_x *sxp);
 int copy_xattrs(const char *source, const char *dest);
 int send_xattr(int f, stat_x *sxp);
 int xattr_diff(struct file_struct *file, stat_x *sxp, int find_all);
 void send_xattr_request(const char *fname, struct file_struct *file, int f_out);
