          "# http://curl.haxx.se/docs/http-cookies.html\n"

          "# This file was generated by libcurl! Edit at your own risk.\n\n",

          out);



    for(co = c->cookies; co; co = co->next) {

      if(!co->domain)

        continue;

      format_ptr = get_netscape_format(co);

      if(format_ptr == NULL) {

        fprintf(out, "#\n# Fatal libcurl error\n");

