  /* Prepend header comment.  */

  fprintf(ofp, "/*\n * DO NOT EDIT\n * This file is generated by:\n");

  fprintf(ofp, " * %s\n */\n\n", argv[0]);

  fprintf(ofp, "#include <stdio.h>\n\n");

  

  /* Split file up in 1024-byte chunks.  */

