          "# This file was generated by libcurl! Edit at your own risk.\n\n",

          out);

    co = c->cookies;



    while(co) {

      fprintf(out,

              "%s%s\t" /* domain */

              "%s\t" /* tailmatch */

              "%s\t" /* path */

              "%s\t" /* secure */

              "%u\t" /* expires */

              "%s\t" /* name */

              "%s\n", /* value */



              /* Make sure all domains are prefixed with a dot if they allow

                 tailmatching. This is Mozilla-style. */

              (co->tailmatch && co->domain && co->domain[0] != '.')? ".":"",

              co->domain?co->domain:"unknown",

              co->tailmatch?"TRUE":"FALSE",

              co->path?co->path:"/",

              co->secure?"TRUE":"FALSE",

              (unsigned int)co->expires,

