    char *format_ptr;

    fputs("# Netscape HTTP Cookie File\n"
          "# http://curlm.haxx.se/rfc/cookie_spec.html\n"
          "# This file was generated by libcurl! Edit at your own risk.\n\n",
          out);
    co = c->cookies;

    while(co) {
      format_ptr = get_netscape_format(co);
      if (format_ptr == NULL) {
        fprintf(out, "#\n# Fatal libcurl error\n");
        return 1;
      }
      fprintf(out, "%s\n", format_ptr);
