    s[j++]="  if not mt.declared[n] and debug.getinfo(2) then\n";
    s[j++]="    local w = debug.getinfo(2, \"S\").what\n";
    s[j++]="    if w ~= \"main\" and w ~= \"C\" then\n";
    s[j++]="      error(\"assignment to undeclared global variable '\"..n..\"'\", 2)\n";
    s[j++]="    end\n";
    s[j++]="    mt.declared[n] = true\n";
    s[j++]="  end\n";
    s[j++]="  rawset(t, n, v)\n";
    s[j++]="end\n";
    s[j++]="mt.__index = function (t, n)\n";
    s[j++]="  if debug.getinfo(2) and not mt.declared[n] and debug.getinfo(2, \"S\").what ~= \"C\" then\n";
    s[j++]="    error(\"global variable '\"..n..\"' is not declared\", 2)\n";
    s[j++]="  end\n";
    s[j++]="  return rawget(t, n)\n";
    s[j++]="end\n";
    s[j++]="function global(...)\n";
    s[j++]="  local nargs = select(\"#\",...)\n";
    s[j++]="  for i = 1, nargs do\n";
    s[j++]="    local v = select(i,...)\n";
    s[j++]="    mt.declared[v] = true\n";
    s[j++]="  end\n";
    s[j++]="end\n";
    s[j++]=NULL;

    for (j = 0; s[j] != NULL; j++) code = sdscatlen(code,s[j],strlen(s[j]));
