# CMake generated Testfile for 
# Source directory: /data/download/cmake/cmake-master/Tests/CMakeOnly
# Build directory: /data/download/cmake/cmake-master/Tests/CMakeOnly
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(CMakeOnly.LinkInterfaceLoop "/data/download/cmake/cmake-master/bin/cmake" "-DTEST=LinkInterfaceLoop" "-P" "/data/download/cmake/cmake-master/Tests/CMakeOnly/Test.cmake")
set_tests_properties(CMakeOnly.LinkInterfaceLoop PROPERTIES  TIMEOUT "90")
add_test(CMakeOnly.CheckSymbolExists "/data/download/cmake/cmake-master/bin/cmake" "-DTEST=CheckSymbolExists" "-P" "/data/download/cmake/cmake-master/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CheckCXXSymbolExists "/data/download/cmake/cmake-master/bin/cmake" "-DTEST=CheckCXXSymbolExists" "-P" "/data/download/cmake/cmake-master/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CheckCXXCompilerFlag "/data/download/cmake/cmake-master/bin/cmake" "-DTEST=CheckCXXCompilerFlag" "-P" "/data/download/cmake/cmake-master/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CheckLanguage "/data/download/cmake/cmake-master/bin/cmake" "-DTEST=CheckLanguage" "-P" "/data/download/cmake/cmake-master/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CheckStructHasMember "/data/download/cmake/cmake-master/bin/cmake" "-DTEST=CheckStructHasMember" "-P" "/data/download/cmake/cmake-master/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CompilerIdC "/data/download/cmake/cmake-master/bin/cmake" "-DTEST=CompilerIdC" "-P" "/data/download/cmake/cmake-master/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CompilerIdCXX "/data/download/cmake/cmake-master/bin/cmake" "-DTEST=CompilerIdCXX" "-P" "/data/download/cmake/cmake-master/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.AllFindModules "/data/download/cmake/cmake-master/bin/cmake" "-DTEST=AllFindModules" "-DCMAKE_ARGS=-DCMake_TEST_CMakeOnly.AllFindModules_NO_VERSION=" "-P" "/data/download/cmake/cmake-master/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.SelectLibraryConfigurations "/data/download/cmake/cmake-master/bin/cmake" "-DTEST=SelectLibraryConfigurations" "-P" "/data/download/cmake/cmake-master/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.TargetScope "/data/download/cmake/cmake-master/bin/cmake" "-DTEST=TargetScope" "-P" "/data/download/cmake/cmake-master/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.find_library "/data/download/cmake/cmake-master/bin/cmake" "-DTEST=find_library" "-P" "/data/download/cmake/cmake-master/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.find_path "/data/download/cmake/cmake-master/bin/cmake" "-DTEST=find_path" "-P" "/data/download/cmake/cmake-master/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.ProjectInclude "/data/download/cmake/cmake-master/bin/cmake" "-DTEST=ProjectInclude" "-DCMAKE_ARGS=-DCMAKE_PROJECT_ProjectInclude_INCLUDE=/data/download/cmake/cmake-master/Tests/CMakeOnly/ProjectInclude/include.cmake" "-P" "/data/download/cmake/cmake-master/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-PythonLibs_2 "/data/download/cmake/cmake-master/bin/cmake" "-DTEST=MajorVersionSelection-PythonLibs_2" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonLibs;-DMAJOR_TEST_VERSION=2;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=PYTHONLIBS_VERSION_STRING" "-P" "/data/download/cmake/cmake-master/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-PythonLibs_3 "/data/download/cmake/cmake-master/bin/cmake" "-DTEST=MajorVersionSelection-PythonLibs_3" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonLibs;-DMAJOR_TEST_VERSION=3;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=PYTHONLIBS_VERSION_STRING" "-P" "/data/download/cmake/cmake-master/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-PythonInterp_2 "/data/download/cmake/cmake-master/bin/cmake" "-DTEST=MajorVersionSelection-PythonInterp_2" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonInterp;-DMAJOR_TEST_VERSION=2;-DMAJOR_TEST_NO_LANGUAGES=TRUE;-DMAJOR_TEST_VERSION_VAR=PYTHON_VERSION_STRING" "-P" "/data/download/cmake/cmake-master/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-PythonInterp_3 "/data/download/cmake/cmake-master/bin/cmake" "-DTEST=MajorVersionSelection-PythonInterp_3" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonInterp;-DMAJOR_TEST_VERSION=3;-DMAJOR_TEST_NO_LANGUAGES=TRUE;-DMAJOR_TEST_VERSION_VAR=PYTHON_VERSION_STRING" "-P" "/data/download/cmake/cmake-master/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-Qt_3 "/data/download/cmake/cmake-master/bin/cmake" "-DTEST=MajorVersionSelection-Qt_3" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=Qt;-DMAJOR_TEST_VERSION=3;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=QT_VERSION_STRING" "-P" "/data/download/cmake/cmake-master/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-Qt_4 "/data/download/cmake/cmake-master/bin/cmake" "-DTEST=MajorVersionSelection-Qt_4" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=Qt;-DMAJOR_TEST_VERSION=4;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=QT_VERSION_STRING" "-P" "/data/download/cmake/cmake-master/Tests/CMakeOnly/Test.cmake")
