fputs(
"              tions  considered  \"insecure\"  to  fail  unless -k/--insecure is\n"
"              used.\n"
"\n"
"              If this option is used twice, the second time will again disable\n"
"              it.\n"
"\n"
"       --key <key>\n"
"              (SSL)  Private key file name. Allows you to provide your private\n"
"              key in this separate file.\n"
"\n"
"              If this option is used several times, the last one will be used.\n"
"\n"
"       --key-type <type>\n"
, stdout);