puts(
"          Make curl display progress information as a progress\n"
"          bar instead of the default statistics.\n"
"\n"
"          If this option is used twice, the second will again\n"
"          disable the progress bar.\n"
"\n"
"     --crlf\n"
"          (FTP) Convert LF to CRLF in upload. Useful for MVS\n"
"          (OS/390).\n"
"\n"
"          If this option is used twice, the second will again\n"
"          disable crlf converting.\n"
"\n"
"     --stderr <file>\n"
"          Redirect all writes to stderr to the specified file\n"
);