"                         The time, in seconds, it took  from  the\n"
"                         start  until  the  file transfer is just\n"
"                         about to begin. This includes  all  pre-\n"
"                         transfer  commands and negotiations that\n"
"                         are specific to  the  particular  proto­\n"
"                         col(s) involved.\n"
"\n"
"          size_download  The  total  amount  of  bytes  that were\n"
"                         downloaded.\n"
"\n"
"          size_upload    The total  amount  of  bytes  that  were\n"
"                         uploaded.\n"
"\n"
"          speed_download The  average  download  speed  that curl\n"
"                         measured for the complete download.\n"
"\n"
"          speed_upload   The average upload speed that curl  mea­\n"
"                         sured for the complete download.\n"
"\n"
"     -x/--proxy <proxyhost[:port]>\n"
"          Use  specified  proxy. If the port number is not speci­\n"
"          fied, it is assumed at port 1080.\n"
"\n"
"     -X/--request <command>\n"
"          (HTTP) Specifies a custom request to use when  communi­\n"
);
 puts(
"          cating  with  the  HTTP  server.  The specified request\n"
"          will be used instead of the standard GET. Read the HTTP\n"
"          1.1 specification for details and explanations.\n"
"\n"
"          (FTP)  Specifies a custom FTP command to use instead of\n"
"          LIST when doing file lists with ftp.\n"
