puts(
"     41   Function  not  found.  A required LDAP function was not\n"
"          found.\n"
"\n"
"     42   Aborted by callback. An application told curl to  abort\n"
"          the operation.\n"
"\n"
"     43   Internal error. A function was called with a bad param�\n"
"          eter.\n"
"\n"
"     44   Internal error. A function was called in a bad order.\n"
"\n"
"     45   Interface error. A specified outgoing  interface  could\n"
"          not be used.\n"
"\n"
"     46   Bad  password  entered. An error was signalled when the\n"
);