puts(
"     49   Malformed telnet option.\n"
"\n"
"     51   The remote peer's SSL certificate wasn't ok\n"
"\n"
"     52   The server didn't reply anything, which here is consid�\n"
"          ered an error.\n"
"\n"
"     53   SSL crypto engine not found\n"
"\n"
"     54   Cannot set SSL crypto engine as default\n"
"\n"
"     55   Failed sending network data\n"
"\n"
"     56   Failure in receiving network data\n"
"\n"
"     57   Share is in use (internal error)\n"
"\n"
"     58   Problem with the local certificate\n"
"\n"
"     59   Couldn't use specified SSL cipher\n"
"\n"
);