fputs(
"              it.\n"
"\n"
"       --sasl-ir\n"
"              Enable  initial  response  in  SASL  authentication.   (Added in\n"
"              7.31.0)\n"
"\n"
"       --service-name <servicename>\n"
"              This option allows you to change the service name for SPNEGO.\n"
"\n"
"              Examples:   --negotiate   --service-name   sockd    would    use\n"
"              sockd/server-name.  (Added in 7.43.0).\n"
"\n"
"       -S, --show-error\n"
"              When  used  with  -s  it  makes curl show an error message if it\n"
, stdout);