fputs(
"              interface name, IP address or host name. An example  could  look\n"
"              like:\n"
"\n"
"               curl --interface eth0:1 https://www.example.com/\n"
"\n"
"              If this option is used several times, the last one will be used.\n"
"\n"
"              See also --dns-interface.\n"
"\n"
"       -4, --ipv4\n"
"              This  option tells curl to resolve names to IPv4 addresses only,\n"
"              and not for example try IPv6.\n"
"\n"
, stdout);