fputs(
"       This option does not change the default proxy protocol (http).\n"
"\n"
"       Without  this  option  curl  would  make a guess based on the host, see\n"
"       --url for details.\n"
"\n"
"       (Added in 7.45.0)\n"
"\n"
"       --proto-redir <protocols>\n"
"              Tells curl to limit what protocols it may use on redirect.  Pro-\n"
"              tocols  denied by --proto are not overridden by this option. See\n"
"              --proto for how protocols are represented.\n"
"\n"
"              Example:\n"
"\n"
, stdout);