"\n"
"     51   The remote peer's SSL certificate wasn't ok\n"
"\n"
"     52   The server didn't reply anything, which here is consid­\n"
"          ered an error.\n"
"\n"
"     XX   There  will  appear  more  error  codes  here in future\n"
"          releases. The existing ones are meant to never  change.\n"
"\n"
"BUGS\n"
"     If you do find bugs, mail them to curl-bug@haxx.se.\n"
"\n"
"AUTHORS / CONTRIBUTORS\n"
"     Daniel  Stenberg  is  the main author, but the whole list of\n"
);
 puts(
"     contributors is found in the separate THANKS file.\n"
"\n"
"WWW\n"
"     http://curl.haxx.se\n"
"FTP\n"
"     ftp://ftp.sunet.se/pub/www/utilities/curl/\n"
"\n"
"SEE ALSO\n"
"     ftp(1), wget(1), snarf(1)\n"
"\n"
"LATEST VERSION\n"
