puts(
"     24   Malformat user. User name badly specified.\n"
"\n"
"     25   FTP couldn't STOR file.  The  server  denied  the  STOR\n"
"          operation.\n"
"\n"
"     26   Read error. Various reading problems.\n"
"\n"
"     27   Out of memory. A memory allocation request failed.\n"
"\n"
"     28   Operation  timeout.  The  specified time-out period was\n"
"          reached according to the conditions.\n"
"\n"
"     29   FTP couldn't set ASCII. The server returned an  unknown\n"
"          reply.\n"
"\n"
);