fputs(
"              protocol.\n"
"\n"
"       2      Failed to initialize.\n"
"\n"
"       3      URL malformed. The syntax was not correct.\n"
"\n"
"       4      A  feature  or  option  that  was  needed to perform the desired\n"
"              request was not enabled or was  explicitly  disabled  at  build-\n"
"              time.  To  make  curl able to do this, you probably need another\n"
"              build of libcurl!\n"
"\n"
"       5      Couldn't resolve proxy.  The  given  proxy  host  could  not  be\n"
"              resolved.\n"
"\n"
, stdout);