fputs(
"       This option does not change the default proxy protocol (http).\n"
"\n"
"       Without this option curl would make a guess  based  on  the  host,  see\n"
"       --url for details.\n"
"\n"
"       (Added in 7.45.0)\n"
"\n"
"       --proto-redir <protocols>\n"
"              Tells  curl to use the listed protocols on redirect. See --proto\n"
"              for how protocols are represented.\n"
"\n"
"              Example:\n"
"\n"
"              --proto-redir -all,http,https\n"
"                     Allow only HTTP and HTTPS on redirect.\n"
"\n"
, stdout);