 "\n"
 , stdout);
  fputs(
 "              --proto-default https ftp.mozilla.org\n"
 "                     https://ftp.mozilla.org\n"
 "\n"
-"       An  unknown or unsupported protocol causes error CURLE_UNSUPPORTED_PRO-\n"
+"       An unknown or unsupported protocol causes error  CURLE_UNSUPPORTED_PRO-\n"
 "       TOCOL.\n"
 "\n"
 "       This option does not change the default proxy protocol (http).\n"
 "\n"
-"       Without this option curl would make a guess  based  on  the  host,  see\n"
+"       Without  this  option  curl  would  make a guess based on the host, see\n"
 "       --url for details.\n"
 "\n"
 "       (Added in 7.45.0)\n"
 "\n"
 "       --proto-redir <protocols>\n"
 , stdout);
  fputs(
-"              Tells  curl to use the listed protocols on redirect. See --proto\n"
+"              Tells curl to use the listed protocols on redirect. See  --proto\n"
 "              for how protocols are represented.\n"
 "\n"
 "              Example:\n"
 "\n"
 "              --proto-redir -all,http,https\n"
 "                     Allow only HTTP and HTTPS on redirect.\n"
 "\n"
-"       By default curl will allow all protocols  on  redirect  except  several\n"
-"       disabled  for security reasons: Since 7.19.4 FILE and SCP are disabled,\n"
+"       By  default  curl  will  allow all protocols on redirect except several\n"
+"       disabled for security reasons: Since 7.19.4 FILE and SCP are  disabled,\n"
 "       and since 7.40.0 SMB and SMBS are also disabled. Specifying all or +all\n"
 , stdout);
  fputs(
-"       enables  all  protocols on redirect, including those disabled for secu-\n"
+"       enables all protocols on redirect, including those disabled  for  secu-\n"
 "       rity.\n"
 "\n"
 "       (Added in 7.20.2)\n"
 "\n"
 "       --proxy-anyauth\n"
-"              Tells curl to pick a suitable authentication method when  commu-\n"
-"              nicating  with  the  given  proxy.  This  might  cause  an extra\n"
+"              Tells  curl to pick a suitable authentication method when commu-\n"
+"              nicating with  the  given  proxy.  This  might  cause  an  extra\n"
 "              request/response round-trip. (Added in 7.13.2)\n"
 "\n"
 "       --proxy-basic\n"
-"              Tells curl to use HTTP Basic authentication  when  communicating\n"
+"              Tells  curl  to use HTTP Basic authentication when communicating\n"
 , stdout);
  fputs(
 "              with the given proxy. Use --basic for enabling HTTP Basic with a\n"
-"              remote host. Basic is the  default  authentication  method  curl\n"
+"              remote  host.  Basic  is  the default authentication method curl\n"
 "              uses with proxies.\n"
 "\n"
 "       --proxy-digest\n"
-"              Tells  curl to use HTTP Digest authentication when communicating\n"
+"              Tells curl to use HTTP Digest authentication when  communicating\n"
 "              with the given proxy. Use --digest for enabling HTTP Digest with\n"
 "              a remote host.\n"
 "\n"
 "       --proxy-negotiate\n"
 , stdout);
  fputs(
-"              Tells  curl  to  use HTTP Negotiate (SPNEGO) authentication when\n"
+"              Tells curl to use HTTP Negotiate  (SPNEGO)  authentication  when\n"
 "              communicating with the given proxy. Use --negotiate for enabling\n"
 "              HTTP Negotiate (SPNEGO) with a remote host. (Added in 7.17.1)\n"
 "\n"
 "       --proxy-ntlm\n"
-"              Tells  curl  to  use HTTP NTLM authentication when communicating\n"
+"              Tells curl to use HTTP NTLM  authentication  when  communicating\n"
 "              with the given proxy. Use --ntlm for enabling NTLM with a remote\n"
 "              host.\n"
 "\n"
 "       --proxy-service-name <servicename>\n"
 , stdout);
  fputs(
-"              This  option  allows  you  to  change the service name for proxy\n"
+"              This option allows you to change  the  service  name  for  proxy\n"
 "              negotiation.\n"
 "\n"
-"              Examples:  --proxy-negotiate   proxy-name   --proxy-service-name\n"
+"              Examples:   --proxy-negotiate   proxy-name  --proxy-service-name\n"
 "              sockd would use sockd/proxy-name.  (Added in 7.43.0).\n"
 "\n"
 "       --proxy1.0 <proxyhost[:port]>\n"
-"              Use  the  specified  HTTP  1.0  proxy. If the port number is not\n"
+"              Use the specified HTTP 1.0 proxy. If  the  port  number  is  not\n"
 "              specified, it is assumed at port 1080.\n"
 "\n"
 , stdout);
  fputs(
-"              The only difference between this and the HTTP proxy option  (-x,\n"
+"              The  only difference between this and the HTTP proxy option (-x,\n"
 "              --proxy), is that attempts to use CONNECT through the proxy will\n"
 "              specify an HTTP 1.0 protocol instead of the default HTTP 1.1.\n"
 "\n"
 "       --pubkey <key>\n"
-"              (SSH) Public key file name. Allows you to  provide  your  public\n"
+"              (SSH)  Public  key  file name. Allows you to provide your public\n"
 "              key in this separate file.\n"
 "\n"
 "              If this option is used several times, the last one will be used.\n"
 , stdout);
  fputs(
 "              (As of 7.39.0, curl attempts to automatically extract the public\n"
-"              key from the private key file, so passing this option is  gener-\n"
+"              key  from the private key file, so passing this option is gener-\n"
 "              ally not required. Note that this public key extraction requires\n"
-"              libcurl to be linked against a copy of libssh2 1.2.8  or  higher\n"
+"              libcurl  to  be linked against a copy of libssh2 1.2.8 or higher\n"
 "              that is itself linked against OpenSSL.)\n"
 "\n"
 "       -q, --disable\n"
-"              If  used  as the first parameter on the command line, the curlrc\n"
+"              If used as the first parameter on the command line,  the  curlrc\n"
 , stdout);
  fputs(
-"              config file will not be read and used. See the -K, --config  for\n"
+"              config  file will not be read and used. See the -K, --config for\n"
 "              details on the default config file search path.\n"
 "\n"
 "       -Q, --quote <command>\n"
-"              (FTP/SFTP)  Send  an arbitrary command to the remote FTP or SFTP\n"
-"              server. Quote commands are sent BEFORE the transfer takes  place\n"
-"              (just  after  the  initial PWD command in an FTP transfer, to be\n"
+"              (FTP/SFTP) Send an arbitrary command to the remote FTP  or  SFTP\n"
+"              server.  Quote commands are sent BEFORE the transfer takes place\n"
+"              (just after the initial PWD command in an FTP  transfer,  to  be\n"
 "              exact). To make commands take place after a successful transfer,\n"
 , stdout);
  fputs(
-"              prefix  them  with  a  dash '-'.  To make commands be sent after\n"
+"              prefix them with a dash '-'.  To make  commands  be  sent  after\n"
 "              curl has changed the working directory, just before the transfer\n"
-"              command(s),  prefix  the  command  with a '+' (this is only sup-\n"
-"              ported for FTP). You may specify any number of commands. If  the\n"
+"              command(s), prefix the command with a '+'  (this  is  only  sup-\n"
+"              ported  for FTP). You may specify any number of commands. If the\n"
 "              server returns failure for one of the commands, the entire oper-\n"
-"              ation will be aborted. You must send syntactically  correct  FTP\n"
+"              ation  will  be aborted. You must send syntactically correct FTP\n"
 , stdout);
  fputs(
-"              commands  as  RFC 959 defines to FTP servers, or one of the com-\n"
-"              mands listed below to SFTP servers.  This  option  can  be  used\n"
-"              multiple  times. When speaking to an FTP server, prefix the com-\n"
+"              commands as RFC 959 defines to FTP servers, or one of  the  com-\n"
+"              mands  listed  below  to  SFTP servers.  This option can be used\n"
+"              multiple times. When speaking to an FTP server, prefix the  com-\n"
 "              mand with an asterisk (*) to make curl continue even if the com-\n"
 "              mand fails as by default curl will stop at first failure.\n"
 "\n"
-"              SFTP  is a binary protocol. Unlike for FTP, curl interprets SFTP\n"
+"              SFTP is a binary protocol. Unlike for FTP, curl interprets  SFTP\n"
 , stdout);
  fputs(
-"              quote commands itself before sending them to the  server.   File\n"
+"              quote  commands  itself before sending them to the server.  File\n"
 "              names may be quoted shell-style to embed spaces or special char-\n"
-"              acters.  Following is the list of all supported SFTP quote  com-\n"
+"              acters.   Following is the list of all supported SFTP quote com-\n"
 "              mands:\n"
 "\n"
 "              chgrp group file\n"
-"                     The  chgrp command sets the group ID of the file named by\n"
-"                     the file operand to the group ID specified by  the  group\n"
+"                     The chgrp command sets the group ID of the file named  by\n"
+"                     the  file  operand to the group ID specified by the group\n"
 , stdout);
  fputs(
 "                     operand. The group operand is a decimal integer group ID.\n"
 "\n"
 "              chmod mode file\n"
-"                     The  chmod  command  modifies  the  file mode bits of the\n"
+"                     The chmod command modifies the  file  mode  bits  of  the\n"
 "                     specified file. The mode operand is an octal integer mode\n"
 "                     number.\n"
 "\n"
 "              chown user file\n"
 "                     The chown command sets the owner of the file named by the\n"
-"                     file operand to the user ID specified by the  user  oper-\n"
+"                     file  operand  to the user ID specified by the user oper-\n"
 , stdout);
  fputs(
 "                     and. The user operand is a decimal integer user ID.\n"
 "\n"
 "              ln source_file target_file\n"
 "                     The ln and symlink commands create a symbolic link at the\n"
-"                     target_file location pointing to  the  source_file  loca-\n"
+"                     target_file  location  pointing  to the source_file loca-\n"
 "                     tion.\n"
 "\n"
 "              mkdir directory_name\n"
-"                     The  mkdir  command  creates  the  directory named by the\n"
+"                     The mkdir command creates  the  directory  named  by  the\n"
 "                     directory_name operand.\n"
 "\n"
 , stdout);
  fputs(
 "              pwd    The pwd command returns the absolute pathname of the cur-\n"
 "                     rent working directory.\n"
 "\n"
 "              rename source target\n"
 "                     The rename command renames the file or directory named by\n"
-"                     the source operand to the destination path named  by  the\n"
+"                     the  source  operand to the destination path named by the\n"
 "                     target operand.\n"
 "\n"
 "              rm file\n"
 "                     The rm command removes the file specified by the file op-\n"
 "                     erand.\n"
 "\n"
 , stdout);
  fputs(
 "              rmdir directory\n"
-"                     The rmdir command removes the directory  entry  specified\n"
+"                     The  rmdir  command removes the directory entry specified\n"
 "                     by the directory operand, provided it is empty.\n"
 "\n"
 "              symlink source_file target_file\n"
 "                     See ln.\n"
 "\n"
 "       -r, --range <range>\n"
-"              (HTTP/FTP/SFTP/FILE)  Retrieve a byte range (i.e a partial docu-\n"
-"              ment) from a HTTP/1.1, FTP or  SFTP  server  or  a  local  FILE.\n"
+"              (HTTP/FTP/SFTP/FILE) Retrieve a byte range (i.e a partial  docu-\n"
+"              ment)  from  a  HTTP/1.1,  FTP  or  SFTP server or a local FILE.\n"
 "              Ranges can be specified in a number of ways.\n"
 "\n"
 , stdout);
  fputs(
 "              0-499     specifies the first 500 bytes\n"
 "\n"
