puts(
"          list of host names that shouldn't go through any proxy.\n"
"          If set to a asterisk\n"
"\n"
"EXIT CODES\n"
"     There exists a bunch of different error codes and their cor�\n"
"     responding error messages that may appear during bad  condi�\n"
"     tions. At the time of this writing, the exit codes are:\n"
"\n"
"     1    Unsupported protocol. This build of curl has no support\n"
"          for this protocol.\n"
"\n"
"     2    Failed to initialize.\n"
"\n"
"     3    URL malformat. The syntax was not correct.\n"
"\n"
);