 "       86     RTSP: mismatch of Session Identifiers\n"
 "\n"
 "       87     unable to parse FTP file list\n"
 "\n"
 "       88     FTP chunk callback reported error\n"
 "\n"
+"       89     No connection available, the session will be queued\n"
+"\n"
 "       XX     More error codes will appear here in future releases. The exist-\n"
 "              ing ones are meant to never change.\n"
 "\n"
-"AUTHORS / CONTRIBUTORS\n"
 , stdout);
  fputs(
-"       Daniel Stenberg is the main author, but the whole list of  contributors\n"
+"AUTHORS / CONTRIBUTORS\n"
+"       Daniel  Stenberg is the main author, but the whole list of contributors\n"
 "       is found in the separate THANKS file.\n"
 "\n"
 "WWW\n"
 "       http://curl.haxx.se\n"
 "\n"
 "FTP\n"
