 "\n"
 "FILES\n"
 "       ~/.curlrc\n"
 "              Default config file, see -K/--config for details.\n"
 "\n"
 "ENVIRONMENT\n"
-"       http_proxy [protocol://]<host>[:port]\n"
 , stdout);
  fputs(
+"       http_proxy [protocol://]<host>[:port]\n"
 "              Sets proxy server to use for HTTP.\n"
 "\n"
 "       HTTPS_PROXY [protocol://]<host>[:port]\n"
 "              Sets proxy server to use for HTTPS.\n"
 "\n"
 "       FTP_PROXY [protocol://]<host>[:port]\n"
 "              Sets proxy server to use for FTP.\n"
 "\n"
 "       ALL_PROXY [protocol://]<host>[:port]\n"
 "              Sets proxy server to use if no protocol-specific proxy is set.\n"
 "\n"
 "       NO_PROXY <comma-separated list of hosts>\n"
-"              list of host names that shouldn’t go through any proxy.  If  set\n"
 , stdout);
  fputs(
+"              list of host names that shouldn’t go through any proxy.  If  set\n"
 "              to a asterisk ’*’ only, it matches all hosts.\n"
 "\n"
 "EXIT CODES\n"
 "       There  exists  a bunch of different error codes and their corresponding\n"
 "       error messages that may appear during bad conditions. At  the  time  of\n"
 "       this writing, the exit codes are:\n"
 "\n"
 "       1      Unsupported protocol. This build of curl has no support for this\n"
 "              protocol.\n"
 "\n"
 "       2      Failed to initialize.\n"
 "\n"
-"       3      URL malformat. The syntax was not correct.\n"
-"\n"
 , stdout);
  fputs(
+"       3      URL malformat. The syntax was not correct.\n"
+"\n"
 "       4      URL user malformatted. The user-part of the URL syntax  was  not\n"
 "              correct.\n"
 "\n"
 "       5      Couldn’t  resolve  proxy.  The  given  proxy  host  could not be\n"
 "              resolved.\n"
 "\n"
