puts(
"      - Frederic Lepied <flepied@mandrakesoft.com>\n"
"      - Georg Horn <horn@koblenz-net.de>\n"
"      - Cris Bailiff <c.bailiff@awayweb.com>\n"
"      - Sterling Hughes <sterling@designmultimedia.com>\n"
"      - S. Moonesamy\n"
"\n"
"WWW\n"
"     http://curl.haxx.se\n"
"\n"
"FTP\n"
"     ftp://ftp.sunet.se/pub/www/utilities/curl/\n"
"\n"
"SEE ALSO\n"
"     ftp(1), wget(1), snarf(1)\n"
"\n"
"LATEST VERSION\n"
"\n"
"  You always find news about what's going on as well as the latest versions\n"
"  from the curl web pages, located at:\n"
"\n"
"        http://curl.haxx.se\n"
"\n"
);