fputs(
"              If this option is used several times, the last one will be used.\n"
"\n"
"       --trace-time\n"
"              Prepends a time stamp to each trace or verbose  line  that  curl\n"
"              displays.  (Added in 7.14.0)\n"
"\n"
"       --tr-encoding\n"
"              (HTTP) Request a compressed Transfer-Encoding response using one\n"
"              of the algorithms libcurl  supports,  and  uncompress  the  data\n"
"              while receiving it.\n"
"\n"
"              (Added in 7.21.6)\n"
"\n"
, stdout);