"\n"
"          This  option is handy to use when you want to store the\n"
"          cookies that a HTTP site  sends  to  you.  The  cookies\n"
"          could then be read in a second curl invoke by using the\n"
"          -b/--cookie option!\n"
"\n"
"          If this option is used several times, the last one will\n"
"          be used.\n"
"\n"
"     -e/--referer <URL>\n"
"          (HTTP) Sends the \"Referer Page\" information to the HTTP\n"
);
 puts(
"          server. This can also be set with the -H/--header  flag\n"
"          of course.  When used with -L/--location you can append\n"
"          \";auto\" to the referer URL to make  curl  automatically\n"
"          set  the  previous  URL  when  it  follows  a Location:\n"
"          header. The \";auto\" string can be used alone,  even  if\n"
"          you don't set an initial referer.\n"
"\n"
"          If this option is used several times, the last one will\n"
"          be used.\n"
"\n"
"     --egd-file <file>\n"
);
 puts(
"          (HTTPS) Specify the path name to the Entropy  Gathering\n"
"          Daemon  socket.  The  socket is used to seed the random\n"
