puts(
"          instead of using its internally preferred: HTTP 1.1.\n"
"\n"
"     -#/--progress-bar\n"
"          Make  curl  display  progress information as a progress\n"
"          bar instead of the default statistics.\n"
"\n"
"          If this option is used twice,  the  second  will  again\n"
"          disable the progress bar.\n"
"\n"
"FILES\n"
"     ~/.curlrc\n"
"          Default config file.\n"
"\n"
"ENVIRONMENT\n"
"     http_proxy [protocol://]<host>[:port]\n"
"          Sets proxy server to use for HTTP.\n"
"\n"
);