 "          prevent that header from appearing.\n"
 "\n"
 "     -i/--include\n"
 "          (HTTP) Include the HTTP-header in the output. The HTTP-\n"
 "          header  includes  things  like server-name, date of the\n"
 "          document, HTTP-version and more...\n"
+"     --interface <name>\n"
+"          Perform an operation using a specified  interface.  You\n"
+"          can  enter  interface name, IP address or host name. An\n"
+"          example could look like:\n"
+"\n"
+"          curl --interface eth0:1 http://www.netscape.com/\n"
+"\n"
 "     -I/--head\n"
 "          (HTTP/FTP) Fetch  the  HTTP-header  only!  HTTP-servers\n"
 "          feature the command HEAD which this uses to get nothing\n"
 "          but the header of a document. When used on a FTP  file,\n"
 "          curl displays the file size only.\n"
 "\n"
+"     --krb4 <level>\n"
+"          (FTP)  Enable  kerberos4  authentication  and  use. The\n"
+);
+ puts(
+"          level must be entered and should  be  one  of  'clear',\n"
+"          'safe',  'confidential'  or 'private'. Should you use a\n"
+"          level that is not one of these, 'private' will  instead\n"
+"          be used.\n"
+"\n"
 "     -K/--config <config file>\n"
 "          Specify  which config file to read curl arguments from.\n"
 "          The config file is a text file in  which  command  line\n"
 "          arguments  can be written which then will be used as if\n"
 "          they were written on the actual command  line.  If  the\n"
 "          first  column  of a config line is a '#' character, the\n"
-);
- puts(
 "          rest of the line will be treated as a comment.\n"
 "\n"
 "          Specify the filename as '-' to make curl read the  file\n"
 "          from stdin.\n"
 "\n"
 "     -l/--list-only\n"
