"          When used with -s it makes curl show error message if\n"
"          it fails.\n"
"\n"
"          If this option is used twice, the second will again\n"
"          disable show error.\n"
"\n"
"     -t/--upload\n"
"          Deprecated. Use '-T -' instead.  Transfer the stdin\n"
"          data to the specified file. Curl will read everything\n"
"          from stdin until EOF and store with the supplied name.\n"
"          If this is used on a http(s) server, the PUT command\n"
"          will be used.\n"
"\n"
"     -T/--upload-file <file>\n"
"          Like -t, but this transfers the specified local file.\n"
"          If there is no file part in the specified URL, Curl\n"
"          will append the local file name. NOTE that you must use\n"
"          a trailing / on the last directory to really prove to\n"
"          Curl that there is no file name or curl will think that\n"
"          your last directory name is the remote file name to\n"
"          use. That will most likely cause the upload operation\n"
"          to fail. If this is used on a http(s) server, the PUT\n"
"          command will be used.\n"
"\n"
"          If this option is used serveral times, the last one\n"
"          will be used.\n"
"\n"
"     -u/--user <user:password>\n"
"          Specify user and password to use when fetching. See\n"
"          README.curl for detailed examples of how to use this.\n"
"          If no password is specified, curl will ask for it\n"
"          interactively.\n"
"\n"
"          If this option is used serveral times, the last one\n"
"          will be used.\n"
"\n"
"     -U/--proxy-user <user:password>\n"
"          Specify user and password to use for Proxy authentica­\n"
"          tion. If no password is specified, curl will ask for it\n"
"          interactively.\n"
"\n"
"          If this option is used serveral times, the last one\n"
"          will be used.\n"
"\n"
