fputs(
"              otherwise  would be used. The data will be appended\n"
"              to the URL with a '?'  separator.\n"
"\n"
"              If used in combination with -I, the POST data  will\n"
"              instead be appended to the URL with a HEAD request.\n"
"\n"
"              If used multiple times, nothing special happens.\n"
"\n"
"       -h/--help\n"
"              Usage help.\n"
"\n"
"       -H/--header <header>\n"
"              (HTTP) Extra header to use when getting a web page.\n"
, stdout);