"              1.3    Use up to TLSv1.3.\n"
"\n"
"       See also --tlsv1.0 and --tlsv1.1 and --tlsv1.2. --tls-max requires that\n"
"       the underlying libcurl was built to support TLS. Added in 7.54.0.\n"
"\n"
"       --tlsauthtype <type>\n"
"              Set  TLS  authentication  type.  Currently,  the  only supported\n"
"              option is \"SRP\",  for  TLS-SRP  (RFC  5054).  If  --tlsuser  and\n"
, stdout);
 fputs(
"              --tlspassword  are specified but --tlsauthtype is not, then this\n"
"              option defaults to \"SRP\".\n"
"\n"
"              Added in 7.21.4.\n"
"\n"
"       --tlspassword\n"
"              Set password for use with the TLS authentication  method  speci-\n"
"              fied with --tlsauthtype. Requires that --tlsuser also be set.\n"
"\n"
"              Added in 7.21.4.\n"
"       --tlsuser <name>\n"
"              Set  username  for use with the TLS authentication method speci-\n"
, stdout);
 fputs(
"              fied with --tlsauthtype. Requires  that  --tlspassword  also  is\n"
"              set.\n"
"\n"
"              Added in 7.21.4.\n"
"\n"
"       --tlsv1.0\n"
"              (TLS)  Forces  curl  to use TLS version 1.0 when connecting to a\n"
"              remote TLS server.\n"
"\n"
"              Added in 7.34.0.\n"
"\n"
"       --tlsv1.1\n"
"              (TLS) Forces curl to use TLS version 1.1 when  connecting  to  a\n"
"              remote TLS server.\n"
"\n"
"              Added in 7.34.0.\n"
"\n"
"       --tlsv1.2\n"
, stdout);
 fputs(
"              (TLS)  Forces  curl  to use TLS version 1.2 when connecting to a\n"
"              remote TLS server.\n"
"\n"
"              Added in 7.34.0.\n"
"\n"
"       --tlsv1.3\n"
"              (TLS) Forces curl to use TLS version 1.3 when  connecting  to  a\n"
"              remote TLS server.\n"
"\n"
"              Note that TLS 1.3 is only supported by a subset of TLS backends.\n"
"              At the time of writing this, those are BoringSSL and NSS only.\n"
"\n"
"              Added in 7.52.0.\n"
"\n"
"       -1, --tlsv1\n"
, stdout);
 fputs(
"              (SSL) Tells curl to use TLS version 1.x when negotiating with  a\n"
"              remote TLS server. That means TLS version 1.0, 1.1 or 1.2.\n"
"\n"
"              See  also  --http1.1  and --http2. -1, --tlsv1 requires that the\n"
"              underlying libcurl was built to support TLS. This  option  over-\n"
"              rides --tlsv1.1 and --tlsv1.2 and --tlsv1.3.\n"
"\n"
"       --tr-encoding\n"
"              (HTTP) Request a compressed Transfer-Encoding response using one\n"
, stdout);
 fputs(
"              of the algorithms curl supports, and uncompress the  data  while\n"
"              receiving it.\n"
"\n"
"              Added in 7.21.6.\n"
"\n"
"       --trace-ascii <file>\n"
"              Enables  a  full  trace  dump of all incoming and outgoing data,\n"
"              including descriptive information, to the given output file. Use\n"
"              \"-\" as filename to have the output sent to stdout.\n"
"\n"
"              This is very similar to --trace, but leaves out the hex part and\n"
, stdout);
 fputs(
"              only shows the ASCII part of the dump. It makes  smaller  output\n"
"              that might be easier to read for untrained humans.\n"
"\n"
"              If this option is used several times, the last one will be used.\n"
"\n"
"              This option overrides --trace and -v, --verbose.\n"
"\n"
"       --trace-time\n"
"              Prepends  a  time  stamp to each trace or verbose line that curl\n"
"              displays.\n"
"\n"
"              Added in 7.14.0.\n"
"\n"
"       --trace <file>\n"
, stdout);
 fputs(
"              Enables a full trace dump of all  incoming  and  outgoing  data,\n"
"              including descriptive information, to the given output file. Use\n"
"              \"-\" as filename to have the output sent to stdout.  Use  \"%\"  as\n"
"              filename to have the output sent to stderr.\n"
"\n"
"              If this option is used several times, the last one will be used.\n"
"\n"
"              This option overrides -v, --verbose and --trace-ascii.\n"
"\n"
