"          (HTTP) Extra header to use when getting a web page. You\n"
"          may specify any number of extra headers. Note that if\n"
"          you should add a custom header that has the same name\n"
"          as one of the internal ones curl would use, your exter­\n"
"          nally set header will be used instead of the internal\n"
"          one. This allows you to make even trickier stuff than\n"
"          curl would normally do. You should not replace inter­\n"
"          nally set headers without knowing perfectly well what\n"
"          you're doing. Replacing an internal header with one\n"
"          without content on the right side of the colon will\n"
"          prevent that header from appearing.\n"
"     -i/--include\n"
"          (HTTP) Include the HTTP-header in the output. The HTTP-\n"
"          header includes things like server-name, date of the\n"
"          document, HTTP-version and more...\n"
"\n"
"     --interface <name>\n"
"          Perform an operation using a specified interface. You\n"
"          can enter interface name, IP address or host name. An\n"
"          example could look like:\n"
"\n"
"          curl --interface eth0:1 http://www.netscape.com/\n"
"\n"
"     -I/--head\n"
"          (HTTP/FTP) Fetch the HTTP-header only! HTTP-servers\n"
"          feature the command HEAD which this uses to get nothing\n"
);
 puts(
"          but the header of a document. When used on a FTP file,\n"
"          curl displays the file size only.\n"
"\n"
"     --krb4 <level>\n"
"          (FTP) Enable kerberos4 authentication and use. The\n"
"          level must be entered and should be one of 'clear',\n"
