puts(
"          should be a file name to read the data from, or - if\n"
"          you want curl to read the data from stdin.  The\n"
"          contents of the file must already be url-encoded. Mul�\n"
"          tiple files can also be specified.\n"
"\n"
"          To post data purely binary, you should instead use the\n"
"          --data-binary option.\n"
"\n"
"          -d/--data is the same as --data-ascii.\n"
"\n"
"          If this option is used serveral times, the ones follow�\n"
"          ing the first will append data.\n"
"\n"
);