 "              This option overrides any previous use of  -x/--proxy,  as  they\n"
 "              are mutually exclusive.\n"
 "\n"
 "              If this option is used several times, the last one will be used.\n"
 "\n"
 "       --socks5-hostname <host[:port]>\n"
-"              Use the specified SOCKS5 proxy (and let the  proxy  resolve  the\n"
+"              Use  the  specified  SOCKS5 proxy (and let the proxy resolve the\n"
 , stdout);
  fputs(
-"              host  name).  If the port number is not specified, it is assumed\n"
+"              host name). If the port number is not specified, it  is  assumed\n"
 "              at port 1080. (Added in 7.18.0)\n"
 "\n"
-"              This option overrides any previous use of  -x/--proxy,  as  they\n"
+"              This  option  overrides  any previous use of -x/--proxy, as they\n"
 "              are mutually exclusive.\n"
 "\n"
 "              If this option is used several times, the last one will be used.\n"
-"              (This option was  previously  wrongly  documented  and  used  as\n"
+"              (This  option  was  previously  wrongly  documented  and used as\n"
 "              --socks without the number appended.)\n"
 "\n"
 "       --socks5 <host[:port]>\n"
 , stdout);
  fputs(
-"              Use  the  specified  SOCKS5  proxy  -  but resolve the host name\n"
-"              locally. If the port number is not specified, it is  assumed  at\n"
+"              Use the specified SOCKS5 proxy  -  but  resolve  the  host  name\n"
+"              locally.  If  the port number is not specified, it is assumed at\n"
 "              port 1080.\n"
 "\n"
-"              This  option  overrides  any previous use of -x/--proxy, as they\n"
+"              This option overrides any previous use of  -x/--proxy,  as  they\n"
 "              are mutually exclusive.\n"
 "\n"
 "              If this option is used several times, the last one will be used.\n"
-"              (This  option  was  previously  wrongly  documented  and used as\n"
+"              (This option was  previously  wrongly  documented  and  used  as\n"
 , stdout);
  fputs(
 "              --socks without the number appended.)\n"
 "       --socks5-gssapi-service <servicename>\n"
 "              The default service name for a socks server is rcmd/server-fqdn.\n"
 "              This option allows you to change it.\n"
 "\n"
 "              Examples:\n"
-"               --socks5  proxy-name  --socks5-gssapi-service sockd   would use\n"
+"               --socks5 proxy-name --socks5-gssapi-service sockd    would  use\n"
 "              sockd/proxy-name\n"
-"               --socks5  proxy-name  --socks5-gssapi-service   sockd/real-name\n"
+"               --socks5   proxy-name  --socks5-gssapi-service  sockd/real-name\n"
 , stdout);
  fputs(
-"              would  use  sockd/real-name  for cases where the proxy-name does\n"
+"              would use sockd/real-name for cases where  the  proxy-name  does\n"
 "              not match the princpal name.\n"
 "               (Added in 7.19.4).\n"
 "\n"
 "       --socks5-gssapi-nec\n"
-"              As part of the gssapi negotiation a protection mode  is  negoti-\n"
-"              ated.  The  rfc1961  says  in  section 4.3/4.4 it should be pro-\n"
-"              tected, but the NEC  reference  implementation  does  not.   The\n"
-"              option  --socks5-gssapi-nec  allows  the unprotected exchange of\n"
+"              As  part  of the gssapi negotiation a protection mode is negoti-\n"
+"              ated. The rfc1961 says in section  4.3/4.4  it  should  be  pro-\n"
+"              tected,  but  the  NEC  reference  implementation does not.  The\n"
+"              option --socks5-gssapi-nec allows the  unprotected  exchange  of\n"
 , stdout);
  fputs(
 "              the protection mode negotiation. (Added in 7.19.4).\n"
 "\n"
 "       --stderr <file>\n"
-"              Redirect all writes to stderr to the specified file instead.  If\n"
-"              the  file  name is a plain '-', it is instead written to stdout.\n"
-"              This option has no point when you're using a shell  with  decent\n"
+"              Redirect  all writes to stderr to the specified file instead. If\n"
+"              the file name is a plain '-', it is instead written  to  stdout.\n"
+"              This  option  has no point when you're using a shell with decent\n"
 "              redirecting capabilities.\n"
 "\n"
 "              If this option is used several times, the last one will be used.\n"
 "\n"
 "       --tcp-nodelay\n"
 , stdout);
