fputs(
"              If this option is used several times, the last  one\n"
"              will be used.\n"
"       --create-dirs\n"
"              When  used  in conjunction with the -o option, curl\n"
"              will create the necessary local directory hierarchy\n"
"              as needed.\n"
"\n"
"       --crlf (FTP)  Convert LF to CRLF in upload. Useful for MVS\n"
"              (OS/390).\n"
"\n"
"              If this option is used twice, the second will again\n"
"              disable crlf converting.\n"
"\n"
"       -d/--data <data>\n"
, stdout);