 "     range, you'll instead get the whole document.\n"
 "\n"
 "     FTP range downloads only support the simple syntax 'start-\n"
 "     stop' (optionally with one of the numbers omitted). It\n"
 "     depends on the non-RFC command SIZE.\n"
 "\n"
+"     If this option is used serveral times, the last one will be\n"
+"     used.\n"
+"\n"
 "     -s/--silent\n"
 "          Silent mode. Don't show progress meter or error mes­\n"
 "          sages.  Makes Curl mute.\n"
 "\n"
+"          If this option is used twice, the second will again\n"
+"          disable mute.\n"
+"\n"
 "     -S/--show-error\n"
 "          When used with -s it makes curl show error message if\n"
 "          it fails.\n"
 "\n"
+"          If this option is used twice, the second will again\n"
+);
+ puts(
+"          disable show error.\n"
+"\n"
 "     -t/--upload\n"
 "          Deprecated. Use '-T -' instead.  Transfer the stdin\n"
 "          data to the specified file. Curl will read everything\n"
 "          from stdin until EOF and store with the supplied name.\n"
 "          If this is used on a http(s) server, the PUT command\n"
 "          will be used.\n"
