"\n"
"       If this option is used several times, the last one will be  used.  Dis-\n"
"       able  the  use  of PORT with --ftp-pasv. Disable the attempt to use the\n"
"       EPRT command instead of PORT by using --disable-eprt.  EPRT  is  really\n"
"       PORT++.\n"
"\n"
"       -q     If  used  as the first parameter on the command line, the curlrc\n"
, stdout);
 fputs(
"              config file will not be read and used. See the  -K/--config  for\n"
"              details on the default config file search path.\n"
"\n"
"       -Q/--quote <command>\n"
"              (FTP/SFTP)  Send  an arbitrary command to the remote FTP or SFTP\n"
"              server. Quote commands are sent BEFORE the transfer takes  place\n"
"              (just  after  the  initial PWD command in an FTP transfer, to be\n"
"              exact). To make commands take place after a successful transfer,\n"
, stdout);
 fputs(
"              prefix  them  with  a  dash '-'.  To make commands be sent after\n"
"              libcurl has changed  the  working  directory,  just  before  the\n"
"              transfer command(s), prefix the command with a '+' (this is only\n"
"              supported for FTP). You may specify any number of  commands.  If\n"
"              the  server  returns failure for one of the commands, the entire\n"
"              operation will be aborted. You must send  syntactically  correct\n"
, stdout);
 fputs(
"              FTP  commands  as  RFC959  defines to FTP servers, or one of the\n"
"              commands listed below to SFTP servers.  This option can be  used\n"
"              multiple times.\n"
"\n"
"              SFTP  is  a  binary protocol. Unlike for FTP, libcurl interprets\n"
"              SFTP quote commands before sending them to the server.   Follow-\n"
"              ing is the list of all supported SFTP quote commands:\n"
"\n"
"              chgrp group file\n"
, stdout);
 fputs(
"                     The  chgrp command sets the group ID of the file named by\n"
"                     the file operand to the group ID specified by  the  group\n"
"                     operand. The group operand is a decimal integer group ID.\n"
"\n"
"              chmod mode file\n"
"                     The chmod command modifies the  file  mode  bits  of  the\n"
"                     specified file. The mode operand is an octal integer mode\n"
"                     number.\n"
"\n"
"              chown user file\n"
, stdout);
 fputs(
"                     The chown command sets the owner of the file named by the\n"
"                     file  operand  to  the  user  ID  specified  by  the user\n"
"                     operand. The user operand is a decimal integer user ID.\n"
"\n"
"              ln source_file target_file\n"
"                     The ln and symlink commands create a symbolic link at the\n"
"                     target_file  location  pointing  to the source_file loca-\n"
"                     tion.\n"
"\n"
"              mkdir directory_name\n"
, stdout);
 fputs(
"                     The mkdir command creates  the  directory  named  by  the\n"
"                     directory_name operand.\n"
"\n"
"              pwd    The pwd command returns the absolute pathname of the cur-\n"
"                     rent working directory.\n"
"\n"
"              rename source target\n"
"                     The rename command renames the file or directory named by\n"
"                     the  source  operand to the destination path named by the\n"
"                     target operand.\n"
"\n"
, stdout);
 fputs(
"              rm file\n"
"                     The rm command removes the file  specified  by  the  file\n"
"                     operand.\n"
"\n"
"              rmdir directory\n"
"                     The  rmdir  command removes the directory entry specified\n"
"                     by the directory operand, provided it is empty.\n"
"\n"
"              symlink source_file target_file\n"
"                     See ln.\n"
"\n"
"       --random-file <file>\n"
"              (SSL) Specify the path name to file containing what will be con-\n"
, stdout);
 fputs(
"              sidered  as  random  data.  The  data is used to seed the random\n"
"              engine for SSL connections.  See also the --egd-file option.\n"
"\n"
"       -r/--range <range>\n"
"              (HTTP/FTP/SFTP/FILE) Retrieve a byte range (i.e a partial  docu-\n"
"              ment)  from  a  HTTP/1.1,  FTP  or  SFTP server or a local FILE.\n"
"              Ranges can be specified in a number of ways.\n"
"\n"
"              0-499     specifies the first 500 bytes\n"
"\n"
, stdout);
 fputs(
