 "              ify  it  \"@filename\"  and  to  tell curl to read the format from\n"
 "              stdin you write \"@-\".\n"
 "\n"
 "              The variables present in the output format will  be  substituted\n"
 "              by  the  value or text that curl thinks fit, as described below.\n"
 "              All variables are specified as %{variable_name} and to output  a\n"
-"              normal  %  you  just  it them as %%. You can output a newline by\n"
+"              normal  % you just write them as %%. You can output a newline by\n"
 , stdout);
  fputs(
 "              using \\n, a carriage return with \\r and a tab space with \\t.\n"
 "\n"
-"              NOTE: The %-letter is a special letter in the win32-environment,\n"
+"              NOTE: The %-symbol is a special symbol in the win32-environment,\n"
 "              where  all  occurrences  of  %  must  be doubled when using this\n"
 "              option.\n"
 "\n"
 "              The variables available at this point are:\n"
 "\n"
 "              url_effective  The URL that was fetched last. This is most mean-\n"
