"  or use the more appropriate FTPS way to get the same file:\n"
"\n"
"        curl --ftp-ssl ftp://files.are.secure.com/secrets.txt\n"
"\n"
"  Get a file from an SSH server using SFTP:\n"
"\n"
"        curl -u username sftp://example.com/etc/issue\n"
"\n"
"  Get a file from an SSH server using SCP using a private key\n"
"  (not password-protected) to authenticate:\n"
"\n"
, stdout);
 fputs(
"        curl -u username: --key ~/.ssh/id_rsa \\\n"
"             scp://example.com/~/file.txt\n"
"\n"
"  Get a file from an SSH server using SCP using a private key\n"
"  (password-protected) to authenticate:\n"
"\n"
"        curl -u username: --key ~/.ssh/id_rsa --pass private_key_password \\\n"
"             scp://example.com/~/file.txt\n"
"\n"
"  Get the main page from an IPv6 web server:\n"
"\n"
"        curl \"http://[2001:1890:1112:1::20]/\"\n"
"\n"
"DOWNLOAD TO A FILE\n"
"\n"
"  Get a web page and store in a local file with a specific name:\n"
"\n"
, stdout);
 fputs(
"        curl -o thatpage.html http://www.netscape.com/\n"
"\n"
"  Get a web page and store in a local file, make the local file get the name\n"
"  of the remote document (if no file name part is specified in the URL, this\n"
"  will fail):\n"
"\n"
"        curl -O http://www.netscape.com/index.html\n"
"\n"
"  Fetch two files and store them with their remote names:\n"
