fputs(
"              initial referer.\n"
"\n"
"              If this option is used several times, the last  one\n"
"              will be used.\n"
"       --environment\n"
"              (RISC  OS  ONLY)  Sets a range of environment vari-\n"
"              ables, using the names the -w option  supports,  to\n"
"              easier allow extraction of useful information after\n"
"              having run curl.\n"
"\n"
"              If this option is used several times,  each  occur-\n"
"              rence will toggle this on/off.\n"
"\n"
, stdout);