 "          card session cookies when they're closed  down.  (Added\n"
 "          in 7.9.7)\n"
 "\n"
 "          If  this  option is used several times, each occurrence\n"
 "          will toggle this on/off.\n"
 "\n"
+"     -k/--insecure\n"
+"          (SSL) This option explicitly  allows  curl  to  perform\n"
+"          \"insecure\" SSL connections and transfers. Starting with\n"
+);
+ puts(
+"          curl 7.10, all SSL connections will be attempted to  be\n"
+"          made   secure   by  using  the  CA  certificate  bundle\n"
+"          installed by default. This makes all  connections  con­\n"
+"          sidered  \"insecure\"  to  fail  unless  -k/--insecure is\n"
+"          used.\n"
+"\n"
+"          If this option is used  twice,  the  second  time  will\n"
+"          again disable it.\n"
 "     --krb4 <level>\n"
-"          (FTP) Enable  kerberos4  authentication  and  use.  The\n"
-"          level  must  be  entered  and should be one of 'clear',\n"
+"          (FTP)  Enable  kerberos4  authentication  and  use. The\n"
 );
  puts(
-"          'safe', 'confidential' or 'private'. Should you  use  a\n"
-"          level  that is not one of these, 'private' will instead\n"
+"          level must be entered and should  be  one  of  'clear',\n"
+"          'safe',  'confidential'  or 'private'. Should you use a\n"
+"          level that is not one of these, 'private' will  instead\n"
 "          be used.\n"
 "\n"
 "          If this option is used several times, the last one will\n"
 "          be used.\n"
 "\n"
 "     -K/--config <config file>\n"
-"          Specify  which config file to read curl arguments from.\n"
-"          The config file is a text file in  which  command  line\n"
-"          arguments  can be written which then will be used as if\n"
+"          Specify which config file to read curl arguments  from.\n"
+"          The  config  file  is a text file in which command line\n"
 );
  puts(
-"          they were written on the actual command  line.  Options\n"
+"          arguments can be written which then will be used as  if\n"
+"          they  were  written on the actual command line. Options\n"
 "          and their parameters must be specified on the same con­\n"
-"          fig file line. If the parameter  is  to  contain  white\n"
-"          spaces,  the  parameter must be inclosed within quotes.\n"
-"          If the first column of a config line is a  '#'  charac­\n"
+"          fig  file  line.  If  the parameter is to contain white\n"
+"          spaces, the parameter must be inclosed  within  quotes.\n"
+"          If  the  first column of a config line is a '#' charac­\n"
 "          ter, the rest of the line will be treated as a comment.\n"
 "\n"
-"          Specify the filename as '-' to make curl read the  file\n"
-"          from stdin.\n"
-"\n"
 );
  puts(
-"          Note  that  to  be  able to specify a URL in the config\n"
-"          file, you need to specify it using  the  --url  option,\n"
-"          and  not by simply writing the URL on its own line. So,\n"
+"          Specify  the filename as '-' to make curl read the file\n"
+"          from stdin.\n"
+"\n"
+"          Note that to be able to specify a  URL  in  the  config\n"
+"          file,  you  need  to specify it using the --url option,\n"
+"          and not by simply writing the URL on its own line.  So,\n"
 "          it could look similar to this:\n"
 "\n"
 "          url = \"http://curl.haxx.se/docs/\"\n"
 "\n"
 "          This option can be used multiple times.\n"
 "\n"
-"     -l/--list-only\n"
-"          (FTP) When listing an FTP directory, this switch forces\n"
-"          a  name-only  view.   Especially  useful if you want to\n"
+"     --limit-rate <speed>\n"
 );
  puts(
-"          machine-parse the contents of an  FTP  directory  since\n"
-"          the  normal  directory view doesn't use a standard look\n"
+"          Specify the maximum transfer rate you want curl to use.\n"
+"          This feature is useful if you have a limited  pipe  and\n"
+"          you'd prefer you have your transfer not use your entire\n"
+"          bandwidth.\n"
+"\n"
+"          The given speed is measured in bytes/second,  unless  a\n"
+"          suffix is appended. Appending 'k' or 'K' will count the\n"
+"          number as kilobytes, 'm' or M' makes it megabytes while\n"
+"          'g'  or  'G' makes it gigabytes. Examples: 200K, 3m and\n"
+"          1G.\n"
+"\n"
+);
+ puts(
+"          This option was introduced in curl 7.9.9.\n"
+"\n"
+"          If this option is used several times, the last one will\n"
+"          be used.\n"
+"\n"
+"     -l/--list-only\n"
+"          (FTP) When listing an FTP directory, this switch forces\n"
+"          a name-only view.  Especially useful  if  you  want  to\n"
+"          machine-parse  the  contents  of an FTP directory since\n"
+"          the normal directory view doesn't use a  standard  look\n"
 "          or format.\n"
 "\n"
-"          This option causes an FTP  NLST  command  to  be  sent.\n"
-"          Some  FTP  servers list only files in their response to\n"
-"          NLST; they do not include subdirectories  and  symbolic\n"
+);
+ puts(
+"          This  option  causes  an  FTP  NLST command to be sent.\n"
+"          Some FTP servers list only files in their  response  to\n"
+"          NLST;  they  do not include subdirectories and symbolic\n"
 "          links.\n"
 "\n"
-"          If  this  option  is  used twice, the second will again\n"
+"          If this option is used twice,  the  second  will  again\n"
 "          disable list only.\n"
 "\n"
 "     -L/--location\n"
+"          (HTTP/HTTPS)  If  the server reports that the requested\n"
+"          page has  a  different  location  (indicated  with  the\n"
 );
  puts(
-"          (HTTP/HTTPS) If the server reports that  the  requested\n"
-"          page  has  a  different  location  (indicated  with the\n"
-"          header line Location:) this flag will let curl  attempt\n"
+"          header  line Location:) this flag will let curl attempt\n"
 "          to reattempt the get on the new place. If used together\n"
 "          with -i or -I, headers from all requested pages will be\n"
-"          shown.  If  this  flag is used when making a HTTP POST,\n"
+"          shown. If this flag is used when making  a  HTTP  POST,\n"
 "          curl will automatically switch to GET after the initial\n"
 "          POST has been done.\n"
 "\n"
-);
- puts(
-"          If  this  option  is  used twice, the second will again\n"
+"          If this option is used twice,  the  second  will  again\n"
 "          disable location following.\n"
 "\n"
 "     -m/--max-time <seconds>\n"
-"          Maximum time  in  seconds  that  you  allow  the  whole\n"
-"          operation  to take.  This is useful for preventing your\n"
-"          batch jobs from hanging for hours due to slow  networks\n"
-"          or  links going down.  This doesn't work fully in win32\n"
-"          systems.  See also the --connect-timeout option.\n"
-"\n"
 );
  puts(
+"          Maximum time in seconds that you allow the whole opera­\n"
+"          tion to take.  This is useful for preventing your batch\n"
+"          jobs  from  hanging  for  hours due to slow networks or\n"
+"          links going down.  This doesn't  work  fully  in  win32\n"
+"          systems.  See also the --connect-timeout option.\n"
+"\n"
 "          If this option is used several times, the last one will\n"
 "          be used.\n"
 "\n"
 "     -M/--manual\n"
 "          Manual. Display the huge help text.\n"
 "\n"
 "     -n/--netrc\n"
-"          Makes  curl  scan  the  .netrc  file in the user's home\n"
-"          directory for login name and password.  This  is  typi­\n"
-"          cally  used  for  ftp  on unix. If used with http, curl\n"
-"          will enable user authentication. See netrc(4) or ftp(1)\n"
-"          for  details on the file format. Curl will not complain\n"
 );
  puts(
-"          if that file hasn't the right  permissions  (it  should\n"
+"          Makes curl scan the .netrc  file  in  the  user's  home\n"
+"          directory  for  login  name and password. This is typi­\n"
+"          cally used for ftp on unix. If  used  with  http,  curl\n"
+"          will enable user authentication. See netrc(4) or ftp(1)\n"
+"          for details on the file format. Curl will not  complain\n"
+"          if  that  file  hasn't the right permissions (it should\n"
 "          not be world nor group readable). The environment vari­\n"
+);
+ puts(
 "          able \"HOME\" is used to find the home directory.\n"
 "\n"
-"          A quick and very simple  example  of  how  to  setup  a\n"
-"          .netrc   to   allow   curl   to   ftp  to  the  machine\n"
-"          host.domain.com with user name  'myself'  and  password\n"
+"          A  quick  and  very  simple  example  of how to setup a\n"
+"          .netrc  to  allow  curl   to   ftp   to   the   machine\n"
+"          host.domain.com  with  user  name 'myself' and password\n"
 "          'secret' should look similar to:\n"
 "\n"
 "          machine host.domain.com login myself password secret\n"
 "\n"
-);
- puts(
-"          If  this  option  is  used twice, the second will again\n"
+"          If this option is used twice,  the  second  will  again\n"
 "          disable netrc usage.\n"
 "\n"
 "     -N/--no-buffer\n"
-"          Disables the buffering of the output stream. In  normal\n"
+);
+ puts(
+"          Disables  the buffering of the output stream. In normal\n"
 "          work situations, curl will use a standard buffered out­\n"
-"          put stream that will have the effect that it will  out­\n"
-"          put  the  data  in chunks, not necessarily exactly when\n"
-"          the data arrives.  Using this option will disable  that\n"
+"          put  stream that will have the effect that it will out­\n"
+"          put the data in chunks, not  necessarily  exactly  when\n"
+"          the  data arrives.  Using this option will disable that\n"
 "          buffering.\n"
 "\n"
-);
- puts(
-"          If  this  option  is  used twice, the second will again\n"
+"          If this option is used twice,  the  second  will  again\n"
 "          switch on buffering.\n"
 "\n"
 "     -o/--output <file>\n"
-"          Write output to <file> instead of stdout.  If  you  are\n"
+);
+ puts(
+"          Write  output  to  <file> instead of stdout. If you are\n"
 "          using {} or [] to fetch multiple documents, you can use\n"
-"          '#' followed by a number in the <file> specifier.  That\n"
-"          variable  will  be replaced with the current string for\n"
+"          '#'  followed by a number in the <file> specifier. That\n"
+"          variable will be replaced with the current  string  for\n"
 "          the URL being fetched. Like in:\n"
 "\n"
 "            curl http://{one,two}.site.com -o \"file_#1.txt\"\n"
 "\n"
-);
- puts(
 "          or use several variables like:\n"
+"\n"
 "            curl http://{site,host}.host[1-5].com -o \"#1_#2\"\n"
 "\n"
-"          You may use this option as many times as you have  num­\n"
+);
+ puts(
+"          You  may use this option as many times as you have num­\n"
 "          ber of URLs.\n"
 "\n"
 "     -O/--remote-name\n"
 "          Write output to a local file named like the remote file\n"
 "          we get. (Only the file part of the remote file is used,\n"
 "          the path is cut off.)\n"
 "\n"
-"          You  may use this option as many times as you have num­\n"
+"          You may use this option as many times as you have  num­\n"
 "          ber of URLs.\n"
 "\n"
 "     -p/--proxytunnel\n"
+"          When an HTTP proxy is used, this option will cause non-\n"
 );
  puts(
-"          When an HTTP proxy is used, this option will cause non-\n"
-"          HTTP  protocols  to attempt to tunnel through the proxy\n"
-"          instead of merely using it to do HTTP-like  operations.\n"
+"          HTTP protocols to attempt to tunnel through  the  proxy\n"
+"          instead  of merely using it to do HTTP-like operations.\n"
 "          The tunnel approach is made with the HTTP proxy CONNECT\n"
-"          request and requires that the proxy allows direct  con­\n"
-"          nect  to  the  remote  port number curl wants to tunnel\n"
+"          request  and requires that the proxy allows direct con­\n"
+"          nect to the remote port number  curl  wants  to  tunnel\n"
 "          through to.\n"
 "\n"
-"          If this option is used twice,  the  second  will  again\n"
-);
- puts(
+"          If  this  option  is  used twice, the second will again\n"
 "          disable proxy tunnel.\n"
 "\n"
 "     -P/--ftpport <address>\n"
-"          (FTP)  Reverses  the initiator/listener roles when con­\n"
-"          necting with ftp. This switch makes Curl use  the  PORT\n"
-"          command  instead  of  PASV. In practice, PORT tells the\n"
+);
+ puts(
+"          (FTP) Reverses the initiator/listener roles  when  con­\n"
+"          necting  with  ftp. This switch makes Curl use the PORT\n"
+"          command instead of PASV. In practice,  PORT  tells  the\n"
 "          server to connect to the client's specified address and\n"
-"          port,  while PASV asks the server for an ip address and\n"
+"          port, while PASV asks the server for an ip address  and\n"
 "          port to connect to. <address> should be one of:\n"
 "\n"
+"          interface   i.e  \"eth0\" to specify which interface's IP\n"
 );
  puts(
-"          interface   i.e \"eth0\" to specify which interface's  IP\n"
 "                      address you want to use  (Unix only)\n"
 "\n"
 "          IP address  i.e \"192.168.10.1\" to specify exact IP num­\n"
 "                      ber\n"
 "\n"
 "          host name   i.e \"my.host.domain\" to specify machine\n"
 "\n"
-"          -           (any single-letter string) to make it  pick\n"
+"          -           (any  single-letter string) to make it pick\n"
 "                      the machine's default\n"
 "\n"
-"     If  this  option is used several times, the last one will be\n"
+"     If this option is used several times, the last one  will  be\n"
 "     used.\n"
 "\n"
+"     -q   If used as the first parameter on the command line, the\n"
 );
  puts(
-"     -q   If used as the first parameter on the command line, the\n"
-"          $HOME/.curlrc  file will not be read and used as a con­\n"
+"          $HOME/.curlrc file will not be read and used as a  con­\n"
 "          fig file.\n"
 "\n"
 "     -Q/--quote <comand>\n"
-"          (FTP) Send an  arbitrary  command  to  the  remote  FTP\n"
-"          server,  by  using the QUOTE command of the server. Not\n"
-"          all servers support this command, and the set of  QUOTE\n"
-"          commands  are  server specific! Quote commands are sent\n"
+"          (FTP)  Send  an  arbitrary  command  to  the remote FTP\n"
+"          server, by using the QUOTE command of the  server.  Not\n"
+"          all  servers support this command, and the set of QUOTE\n"
+"          commands are server specific! Quote commands  are  sent\n"
+"          BEFORE  the  transfer is taking place. To make commands\n"
 );
  puts(
-"          BEFORE the transfer is taking place. To  make  commands\n"
-"          take  place  after  a  successful transfer, prefix them\n"
+"          take place after a  successful  transfer,  prefix  them\n"
 "          with a dash '-'. You may specify any amount of commands\n"
-"          to  be run before and after the transfer. If the server\n"
-"          returns failure for one of  the  commands,  the  entire\n"
+"          to be run before and after the transfer. If the  server\n"
+"          returns  failure  for  one  of the commands, the entire\n"
 "          operation will be aborted.\n"
 "\n"
 "          This option can be used multiple times.\n"
 "\n"
 "     --random-file <file>\n"
+"          (HTTPS) Specify the path name to file  containing  what\n"
 );
  puts(
-"          (HTTPS)  Specify  the path name to file containing what\n"
-"          will be considered as random data. The data is used  to\n"
-"          seed  the  random engine for SSL connections.  See also\n"
+"          will  be considered as random data. The data is used to\n"
+"          seed the random engine for SSL connections.   See  also\n"
 "          the --edg-file option.\n"
 "\n"
 "     -r/--range <range>\n"
-"          (HTTP/FTP) Retrieve a byte range (i.e a  partial  docu­\n"
-"          ment)  from  a  HTTP/1.1  or  FTP server. Ranges can be\n"
+"          (HTTP/FTP)  Retrieve  a byte range (i.e a partial docu­\n"
+"          ment) from a HTTP/1.1 or  FTP  server.  Ranges  can  be\n"
 "          specified in a number of ways.\n"
-"\n"
 "          0-499     specifies the first 500 bytes\n"
 "\n"
-);
- puts(
 "          500-999   specifies the second 500 bytes\n"
 "\n"
+);
+ puts(
 "          -500      specifies the last 500 bytes\n"
 "\n"
 "          9500      specifies the bytes from offset 9500 and for­\n"
 "                    ward\n"
 "\n"
 "          0-0,-1    specifies the first and last byte only(*)(H)\n"
