fputs(
"              Turn   on   the   TCP_NODELAY   option.   See   the\n"
"              curl_easy_setopt(3) man page for details about this\n"
"              option. (Added in 7.11.2)\n"
"\n"
"              If  this  option  is used several times, each occu�\n"
"              rance toggles this on/off.\n"
"\n"
"       -t/--telnet-option <OPT=val>\n"
"              Pass options  to  the  telnet  protocol.  Supported\n"
"              options are:\n"
"\n"
"              TTYPE=<term> Sets the terminal type.\n"
"\n"
, stdout);