puts(
"     60   Problem with the CA cert (path? permission?)\n"
"\n"
"     61   Unrecognized transfer encoding\n"
"\n"
"     XX   There will appear  more  error  codes  here  in  future\n"
"          releases.  The existing ones are meant to never change.\n"
"\n"
"BUGS\n"
"     If you do find bugs, mail them to curl-bug@haxx.se.\n"
"\n"
"AUTHORS / CONTRIBUTORS\n"
"     Daniel Stenberg is the main author, but the  whole  list  of\n"
"     contributors is found in the separate THANKS file.\n"
"\n"
"WWW\n"
"     http://curl.haxx.se\n"
"FTP\n"
);