 "  Note that curl cannot use persistant connections for transfers that are used\n"
 "  in subsequence curl invokes. Try to stuff as many URLs as possible on the\n"
 "  same command line if they are using the same host, as that'll make the\n"
 "  transfers faster. If you use a http proxy for file transfers, practicly\n"
 "  all transfers will be persistant.\n"
 "\n"
-"  Persistant connections were introduced in curl 7.7.\n"
-"\n"
 "MAILING LISTS\n"
 "\n"
 "  For your convenience, we have several open mailing lists to discuss curl,\n"
+"  its development and things relevant to this. Get all info at\n"
 , stdout);
  fputs(
-"  its development and things relevant to this. Get all info at\n"
 "  http://curl.haxx.se/mail/. The lists available are:\n"
 "\n"
 "  curl-users\n"
 "\n"
 "    Users of the command line tool. How to use it, what doesn't work, new\n"
 "    features, related tools, questions, news, installations, compilations,\n"
