puts(
"     5    Couldn't resolve proxy. The given proxy host could  not\n"
"          be resolved.\n"
"\n"
"     6    Couldn't  resolve  host.  The given remote host was not\n"
"          resolved.\n"
"\n"
"     7    Failed to connect to host.\n"
"\n"
"     8    FTP weird server  reply.  The  server  sent  data  curl\n"
"          couldn't parse.\n"
"\n"
"     9    FTP access denied. The server denied login.\n"
"\n"
"     10   FTP  user/password  incorrect.  Either one or both were\n"
"          not accepted by the server.\n"
"\n"
);