 "       74     No such user (TFTP)\n"
 "\n"
 "       75     Character conversion failed\n"
 "\n"
 "       76     Character conversion functions required\n"
 "\n"
-"       XX     There  will appear more error codes here in future releases. The\n"
+"       77     Problem with reading the SSL CA cert (path? access rights?)\n"
+"\n"
+"       78     The resource referenced in the URL does not exist\n"
+"\n"
+"       79     An unspecified error occurred during the SSH session\n"
+"\n"
+"       80     Failed to shut down the SSL connection\n"
+"\n"
+, stdout);
+ fputs(
+"       XX     There will appear more error codes here in future releases.  The\n"
 "              existing ones are meant to never change.\n"
 "\n"
 "AUTHORS / CONTRIBUTORS\n"
-"       Daniel Stenberg is the main author, but the whole list of  contributors\n"
+"       Daniel  Stenberg is the main author, but the whole list of contributors\n"
 "       is found in the separate THANKS file.\n"
 "\n"
-, stdout);
- fputs(
 "WWW\n"
 "       http://curl.haxx.se\n"
 "\n"
 "FTP\n"
 "       ftp://ftp.sunet.se/pub/www/utilities/curl/\n"
 "\n"
 "SEE ALSO\n"
 "       ftp(1), wget(1)\n"
 "\n"
 "LATEST VERSION\n"
 "\n"
 "  You always find news about what's going on as well as the latest versions\n"
+, stdout);
+ fputs(
 "  from the curl web pages, located at:\n"
 "\n"
 "        http://curl.haxx.se\n"
 "\n"
 "SIMPLE USAGE\n"
 "\n"
