"\n"
"     -O/--remote-name\n"
"          Write output to a local file named like the remote file\n"
"          we get. (Only the file part of the remote file is used,\n"
"          the path is cut off.)\n"
"\n"
);
 puts(
"          You may use this option as many times as you have num­\n"
"          ber of URLs.\n"
"\n"
"     -p/--proxytunnel\n"
"          When an HTTP proxy is used, this option will cause non-\n"
"          HTTP protocols to attempt to tunnel through the proxy\n"
"          instead of merely using it to do HTTP-like operations.\n"
"          The tunnel approach is made with the HTTP proxy CONNECT\n"
"          request and requires that the proxy allows direct con­\n"
"          nect to the remote port number curl wants to tunnel\n"
);
 puts(
"          through to.\n"
"\n"
"          If this option is used twice, the second will again\n"
"          disable proxy tunnel.\n"
"\n"
"     -P/--ftpport <address>\n"
"          (FTP) Reverses the initiator/listener roles when con­\n"
"          necting with ftp. This switch makes Curl use the PORT\n"
"          command instead of PASV. In practice, PORT tells the\n"
"          server to connect to the client's specified address and\n"
"          port, while PASV asks the server for an ip address and\n"
);
 puts(
"          port to connect to. <address> should be one of:\n"
"\n"
"          interface   i.e \"eth0\" to specify which interface's IP\n"
"                      address you want to use  (Unix only)\n"
"\n"
"          IP address  i.e \"192.168.10.1\" to specify exact IP num­\n"
"                      ber\n"
"\n"
"          host name   i.e \"my.host.domain\" to specify machine\n"
"          -           (any single-letter string) to make it pick\n"
"                      the machine's default\n"
"\n"
);
 puts(
"     If this option is used serveral times, the last one will be\n"
"     used.\n"
"\n"
"     -q   If used as the first parameter on the command line, the\n"
"          $HOME/.curlrc file will not be read and used as a con­\n"
"          fig file.\n"
"\n"
"     -Q/--quote <comand>\n"
"          (FTP) Send an arbitrary command to the remote FTP\n"
"          server, by using the QUOTE command of the server. Not\n"
"          all servers support this command, and the set of QUOTE\n"
);
 puts(
"          commands are server specific! Quote commands are sent\n"
"          BEFORE the transfer is taking place. To make commands\n"
"          take place after a successful transfer, prefix them\n"
"          with a dash '-'. You may specify any amount of commands\n"
"          to be run before and after the transfer. If the server\n"
"          returns failure for one of the commands, the entire\n"
"          operation will be aborted.\n"
"\n"
"          This option can be used multiple times.\n"
"\n"
"     --random-file <file>\n"
);
 puts(
"          (HTTPS) Specify the path name to file containing what\n"
"          will be considered as random data. The data is used to\n"
"          seed the random engine for SSL connections.  See also\n"
"          the --edg-file option.\n"
"\n"
"     -r/--range <range>\n"
"          (HTTP/FTP) Retrieve a byte range (i.e a partial docu­\n"
"          ment) from a HTTP/1.1 or FTP server. Ranges can be\n"
"          specified in a number of ways.\n"
"\n"
"          0-499     specifies the first 500 bytes\n"
"\n"
);
 puts(
"          500-999   specifies the second 500 bytes\n"
"\n"
"          -500      specifies the last 500 bytes\n"
"\n"
"          9500      specifies the bytes from offset 9500 and for­\n"
"                    ward\n"
