"          size_header    The total amount of bytes of the down­\n"
"                         loaded headers.\n"
"\n"
"          size_request   The total amount of bytes that were sent\n"
"                         in the HTTP request.\n"
"\n"
"          speed_download The average download speed that curl\n"
"                         measured for the complete download.\n"
"\n"
"          speed_upload   The average upload speed that curl mea­\n"
"                         sured for the complete upload.\n"
"\n"
"     If this option is used serveral times, the last one will be\n"
"     used.\n"
"\n"
"     -x/--proxy <proxyhost[:port]>\n"
"          Use specified proxy. If the port number is not speci­\n"
"          fied, it is assumed at port 1080.\n"
"\n"
"          If this option is used serveral times, the last one\n"
"          will be used.\n"
"\n"
"     -X/--request <command>\n"
"          (HTTP) Specifies a custom request to use when communi­\n"
"          cating with the HTTP server.  The specified request\n"
"          will be used instead of the standard GET. Read the HTTP\n"
"          1.1 specification for details and explanations.\n"
"\n"
"          (FTP) Specifies a custom FTP command to use instead of\n"
"          LIST when doing file lists with ftp.\n"
"\n"
"          If this option is used serveral times, the last one\n"
"          will be used.\n"
"\n"
"     -y/--speed-time <time>\n"
"          If a download is slower than speed-limit bytes per sec­\n"
"          ond during a speed-time period, the download gets\n"
"          aborted. If speed-time is used, the default speed-limit\n"
"          will be 1 unless set with -y.\n"
"\n"
"          If this option is used serveral times, the last one\n"
"          will be used.\n"
"     -Y/--speed-limit <speed>\n"
"          If a download is slower than this given speed, in bytes\n"
"          per second, for speed-time seconds it gets aborted.\n"
"          speed-time is set with -Y and is 30 if not set.\n"
"\n"
"          If this option is used serveral times, the last one\n"
"          will be used.\n"
"\n"
"     -z/--time-cond <date expression>\n"
"          (HTTP) Request to get a file that has been modified\n"
"          later than the given time and date, or one that has\n"
"          been modified before that time. The date expression can\n"
"          be all sorts of date strings or if it doesn't match any\n"
"          internal ones, it tries to get the time from a given\n"
"          file name instead! See the GNU date(1) or curl_get­\n"
"          date(3) man pages for date expression details.\n"
"\n"
"          Start the date expression with a dash (-) to make it\n"
"          request for a document that is older than the given\n"
"          date/time, default is a document that is newer than the\n"
"          specified date/time.\n"
"\n"
"          If this option is used serveral times, the last one\n"
"          will be used.\n"
"\n"
