"       -s, --silent\n"
"              Silent  or  quiet  mode. Don't show progress meter or error mes-\n"
"              sages.  Makes Curl mute. It will still output the data  you  ask\n"
"              for, potentially even to the terminal/stdout unless you redirect\n"
"              it.\n"
"\n"
"       --sasl-ir\n"
"              Enable initial  response  in  SASL  authentication.   (Added  in\n"
"              7.31.0)\n"
"\n"
"       -S, --show-error\n"
, stdout);
 fputs(
"              When  used  with  -s  it  makes curl show an error message if it\n"
"              fails.\n"
"\n"
"       --ssl  (FTP, POP3, IMAP, SMTP) Try to use SSL/TLS for  the  connection.\n"
"              Reverts to a non-secure connection if the server doesn't support\n"
"              SSL/TLS.  See also --ftp-ssl-control and --ssl-reqd for  differ-\n"
"              ent levels of encryption required. (Added in 7.20.0)\n"
"\n"
"              This  option  was formerly known as --ftp-ssl (Added in 7.11.0).\n"
, stdout);
 fputs(
"              That option name can still be used but  will  be  removed  in  a\n"
"              future version.\n"
"\n"
"       --ssl-reqd\n"
"              (FTP,  POP3,  IMAP,  SMTP)  Require  SSL/TLS for the connection.\n"
"              Terminates the connection if the server doesn't support SSL/TLS.\n"
"              (Added in 7.20.0)\n"
"\n"
"              This  option  was  formerly  known  as  --ftp-ssl-reqd (added in\n"
"              7.15.5). That option name can still be used but will be  removed\n"
, stdout);
 fputs(
"              in a future version.\n"
"\n"
"       --ssl-allow-beast\n"
"              (SSL)  This option tells curl to not work around a security flaw\n"
"              in the SSL3 and TLS1.0 protocols known as BEAST.  If this option\n"
"              isn't  used,  the  SSL layer may use work-arounds known to cause\n"
"              interoperability problems with some older  SSL  implementations.\n"
"              WARNING: this option loosens the SSL security, and by using this\n"
, stdout);
 fputs(
"              flag you ask for exactly that.  (Added in 7.25.0)\n"
"\n"
"       --socks4 <host[:port]>\n"
"              Use the specified SOCKS4 proxy. If the port number is not speci-\n"
"              fied, it is assumed at port 1080. (Added in 7.15.2)\n"
"\n"
"              This  option  overrides any previous use of -x, --proxy, as they\n"
"              are mutually exclusive.\n"
"\n"
"              Since 7.21.7, this option is superfluous since you can specify a\n"
, stdout);
 fputs(
"              socks4 proxy with -x, --proxy using a socks4:// protocol prefix.\n"
"              If this option is used several times, the last one will be used.\n"
"\n"
"       --socks4a <host[:port]>\n"
"              Use the specified SOCKS4a proxy. If the port number is not spec-\n"
"              ified, it is assumed at port 1080. (Added in 7.18.0)\n"
"\n"
"              This option overrides any previous use of -x, --proxy,  as  they\n"
"              are mutually exclusive.\n"
"\n"
, stdout);
 fputs(
"              Since 7.21.7, this option is superfluous since you can specify a\n"
"              socks4a proxy with -x, --proxy using a socks4a:// protocol  pre-\n"
"              fix.\n"
"\n"
"              If this option is used several times, the last one will be used.\n"
"\n"
"       --socks5-hostname <host[:port]>\n"
"              Use  the  specified  SOCKS5 proxy (and let the proxy resolve the\n"
"              host name). If the port number is not specified, it  is  assumed\n"
, stdout);
 fputs(
"              at port 1080. (Added in 7.18.0)\n"
"\n"
"              This  option  overrides any previous use of -x, --proxy, as they\n"
"              are mutually exclusive.\n"
"\n"
"              Since 7.21.7, this option is superfluous since you can specify a\n"
"              socks5 hostname proxy with -x, --proxy using a socks5h:// proto-\n"
"              col prefix.\n"
"\n"
"              If this option is used several times, the last one will be used.\n"
, stdout);
 fputs(
"              (This  option  was  previously  wrongly  documented  and used as\n"
"              --socks without the number appended.)\n"
"\n"
"       --socks5 <host[:port]>\n"
"              Use the specified SOCKS5 proxy  -  but  resolve  the  host  name\n"
"              locally.  If  the port number is not specified, it is assumed at\n"
"              port 1080.\n"
"\n"
"              This option overrides any previous use of -x, --proxy,  as  they\n"
"              are mutually exclusive.\n"
"\n"
, stdout);
 fputs(
"              Since 7.21.7, this option is superfluous since you can specify a\n"
"              socks5 proxy with -x, --proxy using a socks5:// protocol prefix.\n"
"              If this option is used several times, the last one will be used.\n"
"              (This  option  was  previously  wrongly  documented  and used as\n"
"              --socks without the number appended.)\n"
"\n"
"              This option (as well as --socks4) does not work with IPV6,  FTPS\n"
"              or LDAP.\n"
"\n"
, stdout);
 fputs(
"       --socks5-gssapi-service <servicename>\n"
"              The default service name for a socks server is rcmd/server-fqdn.\n"
"              This option allows you to change it.\n"
"\n"
"              Examples:  --socks5  proxy-name  --socks5-gssapi-service   sockd\n"
"              would  use sockd/proxy-name --socks5 proxy-name --socks5-gssapi-\n"
"              service sockd/real-name  would  use  sockd/real-name  for  cases\n"
"              where  the proxy-name does not match the principal name.  (Added\n"
, stdout);
 fputs(
"              in 7.19.4).\n"
"\n"
"       --socks5-gssapi-nec\n"
"              As part of the gssapi negotiation a protection mode  is  negoti-\n"
"              ated.  RFC  1961 says in section 4.3/4.4 it should be protected,\n"
"              but the NEC  reference  implementation  does  not.   The  option\n"
"              --socks5-gssapi-nec  allows the unprotected exchange of the pro-\n"
"              tection mode negotiation. (Added in 7.19.4).\n"
"\n"
"       --stderr <file>\n"
, stdout);
 fputs(
"              Redirect all writes to stderr to the specified file instead.  If\n"
"              the file name is a plain '-', it is instead written to stdout.\n"
"\n"
"              If this option is used several times, the last one will be used.\n"
"\n"
"       -t, --telnet-option <OPT=val>\n"
"              Pass options to the telnet protocol. Supported options are:\n"
