puts(
"     28   Operation timeout. The specified  time-out  period  was\n"
"          reached according to the conditions.\n"
"\n"
"     29   FTP  couldn't set ASCII. The server returned an unknown\n"
"          reply.\n"
"\n"
"     30   FTP PORT failed. The PORT command failed.\n"
"\n"
"     31   FTP couldn't use REST. The REST command failed.\n"
"\n"
"     32   FTP couldn't use SIZE. The  SIZE  command  failed.  The\n"
"          command  is  an  extension to the original FTP spec RFC\n"
"          959.\n"
"\n"
);