fputs(
"              (SSL)  Forces  curl to use TLS version 1 when negotiating with a\n"
"              remote TLS server.\n"
"\n"
"       -2, --sslv2\n"
"              (SSL) Forces curl to use SSL version 2 when negotiating  with  a\n"
"              remote SSL server.\n"
"\n"
"       -3, --sslv3\n"
"              (SSL)  Forces  curl to use SSL version 3 when negotiating with a\n"
"              remote SSL server.\n"
"\n"
"       -4, --ipv4\n"
"              If curl is capable of resolving an address to multiple  IP  ver-\n"
, stdout);