 fputs(
"              libcurl has changed  the  working  directory,  just  before  the\n"
"              transfer command(s), prefix the command with a '+' (this is only\n"
"              supported for FTP). You may specify any number of  commands.  If\n"
"              the  server  returns failure for one of the commands, the entire\n"
"              operation will be aborted. You must send  syntactically  correct\n"
"              FTP  commands  as  RFC959  defines to FTP servers, or one of the\n"
, stdout);
 fputs(
"              commands listed below to SFTP servers.  This option can be  used\n"
"              multiple times.\n"
"\n"
"              SFTP  is  a  binary protocol. Unlike for FTP, libcurl interprets\n"
"              SFTP quote commands before sending them to the server.   Follow-\n"
"              ing is the list of all supported SFTP quote commands:\n"
"\n"
"              chgrp group file\n"
"                     The  chgrp command sets the group ID of the file named by\n"
, stdout);
 fputs(
"                     the file operand to the group ID specified by  the  group\n"
"                     operand. The group operand is a decimal integer group ID.\n"
"\n"
"              chmod mode file\n"
"                     The  chmod  command  modifies  the  file mode bits of the\n"
"                     specified file. The mode operand is an octal integer mode\n"
"                     number.\n"
"\n"
"              chown user file\n"
"                     The chown command sets the owner of the file named by the\n"
, stdout);
 fputs(
"                     file operand to the user ID specified by the  user  oper-\n"
"                     and. The user operand is a decimal integer user ID.\n"
"\n"
"              ln source_file target_file\n"
"                     The ln and symlink commands create a symbolic link at the\n"
"                     target_file location pointing to  the  source_file  loca-\n"
"                     tion.\n"
"\n"
"              mkdir directory_name\n"
"                     The  mkdir  command  creates  the  directory named by the\n"
, stdout);
 fputs(
"                     directory_name operand.\n"
"\n"
"              pwd    The pwd command returns the absolute pathname of the cur-\n"
"                     rent working directory.\n"
"\n"
"              rename source target\n"
"                     The rename command renames the file or directory named by\n"
"                     the source operand to the destination path named  by  the\n"
"                     target operand.\n"
"\n"
"              rm file\n"
, stdout);
 fputs(
"                     The rm command removes the file specified by the file op-\n"
"                     erand.\n"
"\n"
"              rmdir directory\n"
"                     The rmdir command removes the directory  entry  specified\n"
"                     by the directory operand, provided it is empty.\n"
