fputs(
"              erability problems with some older SSL implementations. WARNING:\n"
"              this option loosens the SSL security, and by using this flag you\n"
"              ask for exactly that.\n"
"\n"
"              Added in 7.25.0.\n"
"\n"
"       --ssl-no-revoke\n"
"              (WinSSL)  This  option tells curl to disable certificate revoca-\n"
"              tion checks.  WARNING: this option loosens the SSL security, and\n"
"              by using this flag you ask for exactly that.\n"
"\n"
"              Added in 7.44.0.\n"
"\n"
, stdout);