fputs(
"              If this option is used several times, the last one will be used.\n"
"\n"
"       -s, --silent\n"
"              Silent or quiet mode. Don't show progress meter  or  error  mes-\n"
"              sages.   Makes  Curl mute. It will still output the data you ask\n"
"              for, potentially even to the terminal/stdout unless you redirect\n"
"              it.\n"
"\n"
"       --sasl-ir\n"
"              Enable  initial  response  in  SASL  authentication.   (Added in\n"
"              7.31.0)\n"
"\n"
"       -S, --show-error\n"
, stdout);