puts(
"\n"
"          If this option is used twice,  the  second  will  again\n"
"          disable mute.\n"
"\n"
"     -S/--show-error\n"
"          When  used  with -s it makes curl show error message if\n"
"          it fails.\n"
"\n"
"          If this option is used twice,  the  second  will  again\n"
"          disable show error.\n"
"\n"
"     --stderr <file>\n"
"          Redirect  all  writes  to  stderr to the specified file\n"
"          instead. If the file name is a plain '-', it is instead\n"
);